# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from handheld_device/handheld_device_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class handheld_device_data(genpy.Message):
  _md5sum = "894e9b259d1d4e8448e9e2d9ffed9851"
  _type = "handheld_device/handheld_device_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 device_distance
geometry_msgs/Quaternion device_quat
geometry_msgs/Accel device_accel
int64 device_switch
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['device_distance','device_quat','device_accel','device_switch']
  _slot_types = ['int64','geometry_msgs/Quaternion','geometry_msgs/Accel','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       device_distance,device_quat,device_accel,device_switch

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(handheld_device_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.device_distance is None:
        self.device_distance = 0
      if self.device_quat is None:
        self.device_quat = geometry_msgs.msg.Quaternion()
      if self.device_accel is None:
        self.device_accel = geometry_msgs.msg.Accel()
      if self.device_switch is None:
        self.device_switch = 0
    else:
      self.device_distance = 0
      self.device_quat = geometry_msgs.msg.Quaternion()
      self.device_accel = geometry_msgs.msg.Accel()
      self.device_switch = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q10dq().pack(_x.device_distance, _x.device_quat.x, _x.device_quat.y, _x.device_quat.z, _x.device_quat.w, _x.device_accel.linear.x, _x.device_accel.linear.y, _x.device_accel.linear.z, _x.device_accel.angular.x, _x.device_accel.angular.y, _x.device_accel.angular.z, _x.device_switch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.device_quat is None:
        self.device_quat = geometry_msgs.msg.Quaternion()
      if self.device_accel is None:
        self.device_accel = geometry_msgs.msg.Accel()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.device_distance, _x.device_quat.x, _x.device_quat.y, _x.device_quat.z, _x.device_quat.w, _x.device_accel.linear.x, _x.device_accel.linear.y, _x.device_accel.linear.z, _x.device_accel.angular.x, _x.device_accel.angular.y, _x.device_accel.angular.z, _x.device_switch,) = _get_struct_q10dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q10dq().pack(_x.device_distance, _x.device_quat.x, _x.device_quat.y, _x.device_quat.z, _x.device_quat.w, _x.device_accel.linear.x, _x.device_accel.linear.y, _x.device_accel.linear.z, _x.device_accel.angular.x, _x.device_accel.angular.y, _x.device_accel.angular.z, _x.device_switch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.device_quat is None:
        self.device_quat = geometry_msgs.msg.Quaternion()
      if self.device_accel is None:
        self.device_accel = geometry_msgs.msg.Accel()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.device_distance, _x.device_quat.x, _x.device_quat.y, _x.device_quat.z, _x.device_quat.w, _x.device_accel.linear.x, _x.device_accel.linear.y, _x.device_accel.linear.z, _x.device_accel.angular.x, _x.device_accel.angular.y, _x.device_accel.angular.z, _x.device_switch,) = _get_struct_q10dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q10dq = None
def _get_struct_q10dq():
    global _struct_q10dq
    if _struct_q10dq is None:
        _struct_q10dq = struct.Struct("<q10dq")
    return _struct_q10dq
